[package]
name = "enum_default_generator"
description = "Codegen tool to generate Default trait impls for Gateway API enums"

authors.workspace = true
edition.workspace = true
license.workspace = true
version.workspace = true

[dependencies]
codegen = "0.2.0"
